### ISSUE TITLE
Refactoring von NoForbiddenFeatures

### ISSUE THREAD

**Issue by jan-christiansen** [hsfl-pltp/elm-review-pltp#19]
Bei der Verwendung von `Html.Attributes.class` in `NoForbiddenFeatures` sollte die Fehlermeldung im Unterschied zu anderen Features erklären, dass man statt des `class`-Attributes im Rahmen der Vorlesung Inline-Style-Attribute verwenden soll.

**Comment by jan-christiansen** [comment]
Die Begründung, warum eine spezielle Funktion nicht verwendet werden soll, ist in verschiedenen Fällen häufig unterschiedlich. Ganz zu Anfang gibt es Konzepte, die nicht verwendet werden sollen, die aber später in der Vorlesung eingeführt werden, etwa `List.map`. Dann gibt es Konstrukte, für die in der Vorlesung Alternativen vorgestellt wurden, etwa soll man statt `Html.class` Inline-Styles via `Html.style` verwenden. Außerdem gibt es bei den Decodern den Fall, dass die Funktion `andThen` verwendet wird, die in der Vorlesung aber nicht vorgestellt wurde. Die Aufgabe kann (und soll) hier mit anderen Funktionen gelöst werden. Die Funktion `andThen` wird in der Vorlesung aber nie vorgestellt, daher ist das Feedback-Text für anderen Konstrukte hier nicht zutreffend.

**Comment by mario-koehler** [comment]
Aus unserer bisherigen Diskussion hat sich ergeben, dass die Fehlermeldung eher allgemein formuliert werden sollte und an andere Stelle eine umfangreichere Auflistung der Gründe zu finden sein kann.
