### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by jan-christiansen** [hsfl-pltp/elm-review-pltp#2]
Die Errormeldungen enthalten ein paar englische Rechtschreibfehler. Diese sollten behoben werden. Bei der Gelegenheit bitte direkt überprüfen, ob die Texte verständlich sind.

- [x] Import.NoCoreModule
- [x] Import.NoUnqualified
- [x] NoBooleanComparison
- [x] NoForbiddenFeatures
- [x] NoMinimalRecordAccess
- [x] NoMinimalUnderscorePattern
- [x] NoNegationOfBooleanOperator
- [x] NoSinglePatternCase
- [x] NoUnnecessaryIf
- [x] UseCommutingConversions
- [x] UseConstantsForStyle
- [x] UseEtaReductions
- [x] UseInvertedOperators
- [x] UseLogicalOperators
- [x] UseNamingConventions

**Comment by jan-christiansen** [comment]
Bei der Gelegenheit sollten die Texte direkt einmal überarbeitet werden.

**Comment by mario-koehler** [comment]
Mir sind noch einige kleine Fehler aufgefallen (bzw. meine IDE hat mich darauf aufmerksam gemacht):
- [ ] UseEtaReductions.elm `labmda`
- [ ] UseConstantsForStyle.elm `REPLACEME`. Hier fehlt ein Teil der Dokumentation der Regel
- [ ] NoMinimalUnderscorePattern.elm `Visitorz`
- [ ] NoMinimalRecordAccess.elm `errorsForExpession`
