### ISSUE TITLE
Neue Bibliotheken mit Regeln evaluieren

### ISSUE THREAD

**Issue by jan-christiansen** [hsfl-pltp/elm-review-pltp#21]
Seit elm-review vor mehr als einem Jahr aufgesetzt wurde, gab es anscheinend eine Reihe von neuen Bibliotheken. Es soll evaluiert werden, ob diese sich für den Einsatz in der Vorlesung eignen.

- [x] https://package.elm-lang.org/packages/jfmengels/elm-review-simplify/latest/
- [x] https://package.elm-lang.org/packages/SiriusStarr/elm-review-no-single-pattern-case/latest/
- [x] https://package.elm-lang.org/packages/dillonkearns/elm-review-no-primitive-type-alias/latest/

- https://package.elm-lang.org/packages/jfmengels/elm-review-cognitive-complexity/latest/ - eigenes Ticket: #28 
- https://package.elm-lang.org/packages/jfmengels/elm-review-performance/latest/ - eigenes Ticket: #27 

`Simplify` ersetzt die bisherigen Regeln `NoUnnecessaryIf` und `NoBooleanComparison` und bringt weitere Vereinfachungen
`NoSinglePatternCase` ersetzt die Regel mit gleichem Namen, Kommentar dazu siehe unten
`NoPrimitiveTypeAlias` kommt als neue sinnvolle Regel hinzu

**Comment by mario-koehler** [comment]
weitere Möglichkeiten:
- https://package.elm-lang.org/packages/Arkham/elm-review-no-missing-type-constructor/latest/ als Package, "geklaut" von: https://gist.github.com/jfmengels/e1fd40af3d0e7bde707c0241bf46920f
- https://package.elm-lang.org/packages/jfmengels/elm-review-code-style/latest/
- https://package.elm-lang.org/packages/jfmengels/elm-review-the-elm-architecture/latest/
- https://package.elm-lang.org/packages/jsuder-xx/elm-review-reducible-lambdas/latest/

**Comment by mario-koehler** [comment]
bzgl. `elm-review-no-single-pattern-case`:
Fehlermeldung lautet:
"Single pattern case blocks typically are either unnecessary or overly verbose.
There's usually a more concise way to destructure, e.g. in a function argument,
so consider refactoring."

Ist das aufschlussreich genug für die Studierenden?

In der aktuellen eigenen Fassung steht ein Ansatz mit dabei:
"When an algebraic data type has only a single constructor, you can move the
pattern matching into the function definition.

For example, if you consider a type `type Items = Items Int`, to access the
`Int` value you can define a function as `count (Items n) = n`"

**Comment by jan-christiansen** [comment]
> * https://package.elm-lang.org/packages/Arkham/elm-review-no-missing-type-constructor/latest/ als Package, "geklaut" von: https://gist.github.com/jfmengels/e1fd40af3d0e7bde707c0241bf46920f

Diese Regel ist recht speziell, daher würde ich sie weglassen.

> * https://package.elm-lang.org/packages/jfmengels/elm-review-code-style/latest/

Aus meiner Sicht nicht sehr wichtig, kann man aber schon machen. Also gern hinzufügen.

> * https://package.elm-lang.org/packages/jfmengels/elm-review-the-elm-architecture/latest/

Gilt hier ebenfalls. Ein rekursiven `update` wurde im Labor tatsächlich schon mal verwendet. Das könnte auch tatsächlich mal wieder vorkommen. Also gern hinzufügen.

> * https://package.elm-lang.org/packages/jsuder-xx/elm-review-reducible-lambdas/latest/

Diese Regel sollte durch die Eta-Regel schon abgedeckt sein. Daher würde ich sie nicht hinzufügen.

**Comment by jan-christiansen** [comment]
Ja, die Information von `elm-review-no-single-pattern-case` ist erst mal genug, würde ich sagen. Ich denke, dass ich im Laufe des Semesters vielleicht noch eine einfache Webseite aufsetze, auf der ich Erläuterungen zu den Anmerkungen gebe. Das ist eigentlich viel modularer als die Erklärungen in die Regeln zu integrieren.
