### ISSUE TITLE
elm-review-cognitive-complexity evaluieren

### ISSUE THREAD

**Issue by mario-koehler** [hsfl-pltp/elm-review-pltp#28]
https://github.com/jfmengels/elm-review-cognitive-complexity

**Comment by jan-christiansen** [comment]
Ich habe die Regel mit dem Standardwert 15 verwendet. Die Funktionen, die angemerkt wurden, waren alles zumindest Funktionen, die man sich genauer anschauen sollte. Die Regel sollte in den Laboren auch aktiviert werden.
